{
    'name': 'Grupo Tucan Customs',
    'version': '18.0.1.0.0',
    'summary': 'Modulos con personalizaciones y funcionalidades para Grupo Tucan',
    'description': 'Se unen módulos personalizados y funcionalidades específicas para Grupo Tucan.',
    'license': 'AGPL-3',
    'author': 'Soporte Tecnico Grupo Tucan',
    'website': 'https://grupotucan.com',
    'category': 'Custom',
    'depends': ['base','point_of_sale','product'],
    'data': [],
    #'post_init_hook': '_post_init_hook',
    'installable': True,
    'application': False,
    'auto_install': False,
}